export interface ThemeStyle {
  name: string;
  id: string;
  mainBg: string;
  sidebarBg: string;
  chatBg: string;
  cardBg: string;
  primaryBg: string;
  primaryHoverBg: string;
  primaryText: string;
  accentText: string;
  borderCol: string;
  ringCol: string;
  activeItemBg: string;
  chatWallpaper: string;
  ownBubbleBg: string;
  badgeBg: string;
}

export const themes: { [key: string]: ThemeStyle } = {
  fox: {
    name: "🦊 روباه آتشین (Fox Ember & Black)",
    id: "fox",
    mainBg: "bg-[#090705]",
    sidebarBg: "bg-[#130e09]/95",
    chatBg: "bg-[#090705]",
    cardBg: "bg-[#18110b]/90 border-amber-900/40",
    primaryBg: "bg-gradient-to-r from-orange-600 via-amber-600 to-orange-500 text-white shadow-lg shadow-orange-950/50",
    primaryHoverBg: "hover:from-orange-500 hover:to-amber-500",
    primaryText: "text-amber-400",
    accentText: "text-orange-400",
    borderCol: "border-orange-900/40",
    ringCol: "ring-orange-500/50",
    activeItemBg: "bg-orange-500/15 border-orange-500/50",
    chatWallpaper: "bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-orange-950/40 via-[#0a0805] to-black",
    ownBubbleBg: "bg-gradient-to-r from-orange-600 to-amber-600 text-white border-amber-500/30 shadow-md shadow-orange-950/40",
    badgeBg: "bg-orange-600 text-white"
  },
  telegram: {
    name: "آبی کلاسیک (Telegram Classic)",
    id: "telegram",
    mainBg: "bg-slate-950",
    sidebarBg: "bg-slate-900/90",
    chatBg: "bg-slate-950",
    cardBg: "bg-slate-900/80 border-slate-800",
    primaryBg: "bg-blue-600 text-white shadow-md shadow-blue-950/50",
    primaryHoverBg: "hover:bg-blue-500",
    primaryText: "text-blue-400",
    accentText: "text-blue-300",
    borderCol: "border-slate-800",
    ringCol: "ring-blue-500/50",
    activeItemBg: "bg-blue-600/15 border-blue-500/40",
    chatWallpaper: "bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-blue-950/25 via-slate-950 to-black",
    ownBubbleBg: "bg-blue-600 text-white border-blue-400/20",
    badgeBg: "bg-blue-600 text-white"
  },
  sapphire: {
    name: "یاقوت کبود (Sapphire)",
    id: "sapphire",
    mainBg: "bg-blue-950",
    sidebarBg: "bg-blue-900/85",
    chatBg: "bg-blue-950",
    cardBg: "bg-blue-900/40 border-indigo-900/60",
    primaryBg: "bg-indigo-600 text-white shadow-md",
    primaryHoverBg: "hover:bg-indigo-500",
    primaryText: "text-indigo-400",
    accentText: "text-indigo-300",
    borderCol: "border-indigo-900/60",
    ringCol: "ring-indigo-500/50",
    activeItemBg: "bg-indigo-600/20 border-indigo-500/50",
    chatWallpaper: "bg-[radial-gradient(ellipse_at_bottom_left,_var(--tw-gradient-stops))] from-blue-900/25 via-blue-950 to-slate-950",
    ownBubbleBg: "bg-indigo-600 text-white border-indigo-400/20",
    badgeBg: "bg-indigo-600 text-white"
  },
  emerald: {
    name: "زمرد جنگل (Emerald)",
    id: "emerald",
    mainBg: "bg-zinc-950",
    sidebarBg: "bg-emerald-950/80",
    chatBg: "bg-zinc-950",
    cardBg: "bg-emerald-950/30 border-emerald-900/40",
    primaryBg: "bg-emerald-600 text-white shadow-md",
    primaryHoverBg: "hover:bg-emerald-500",
    primaryText: "text-emerald-400",
    accentText: "text-emerald-300",
    borderCol: "border-emerald-900/40",
    ringCol: "ring-emerald-500/50",
    activeItemBg: "bg-emerald-600/20 border-emerald-500/50",
    chatWallpaper: "bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-emerald-900/15 via-zinc-950 to-zinc-950",
    ownBubbleBg: "bg-emerald-600 text-white border-emerald-400/20",
    badgeBg: "bg-emerald-600 text-white"
  },
  amethyst: {
    name: "غروب آمیتیست (Amethyst)",
    id: "amethyst",
    mainBg: "bg-purple-950",
    sidebarBg: "bg-purple-900/80",
    chatBg: "bg-slate-950",
    cardBg: "bg-purple-950/40 border-purple-900/50",
    primaryBg: "bg-purple-600 text-white shadow-md",
    primaryHoverBg: "hover:bg-purple-500",
    primaryText: "text-purple-400",
    accentText: "text-purple-300",
    borderCol: "border-purple-900/50",
    ringCol: "ring-purple-500/50",
    activeItemBg: "bg-purple-600/20 border-purple-500/50",
    chatWallpaper: "bg-[radial-gradient(ellipse_at_center,_var(--tw-gradient-stops))] from-purple-900/15 via-slate-950 to-slate-950",
    ownBubbleBg: "bg-purple-600 text-white border-purple-400/20",
    badgeBg: "bg-purple-600 text-white"
  },
  cyberpunk: {
    name: "سایبرپانک نئون (Cyberpunk)",
    id: "cyberpunk",
    mainBg: "bg-neutral-950",
    sidebarBg: "bg-zinc-900/90",
    chatBg: "bg-black",
    cardBg: "bg-zinc-900/50 border-fuchsia-900/50",
    primaryBg: "bg-gradient-to-r from-fuchsia-600 to-pink-600 text-white shadow-md shadow-fuchsia-950/50",
    primaryHoverBg: "hover:from-fuchsia-500 hover:to-pink-500",
    primaryText: "text-fuchsia-400",
    accentText: "text-cyan-400",
    borderCol: "border-fuchsia-900/50",
    ringCol: "ring-fuchsia-500/50",
    activeItemBg: "bg-fuchsia-600/20 border-fuchsia-500/50",
    chatWallpaper: "bg-[linear-gradient(to_bottom,_var(--tw-gradient-stops))] from-fuchsia-950/15 via-black to-cyan-950/5",
    ownBubbleBg: "bg-gradient-to-r from-fuchsia-600 to-pink-600 text-white border-fuchsia-400/30",
    badgeBg: "bg-fuchsia-600 text-white"
  },
  sunset: {
    name: "غروب آفتاب (Sunset Warm)",
    id: "sunset",
    mainBg: "bg-stone-950",
    sidebarBg: "bg-amber-950/40",
    chatBg: "bg-stone-950",
    cardBg: "bg-amber-950/20 border-amber-900/30",
    primaryBg: "bg-amber-600 text-white shadow-md",
    primaryHoverBg: "hover:bg-amber-500",
    primaryText: "text-amber-400",
    accentText: "text-orange-400",
    borderCol: "border-amber-900/30",
    ringCol: "ring-amber-500/50",
    activeItemBg: "bg-amber-600/20 border-amber-500/50",
    chatWallpaper: "bg-gradient-to-tr from-stone-950 via-stone-950 to-amber-950/15",
    ownBubbleBg: "bg-amber-600 text-white border-amber-400/20",
    badgeBg: "bg-amber-600 text-white"
  },
  sakura: {
    name: "گیلاس صورتی (Sakura Blossom)",
    id: "sakura",
    mainBg: "bg-rose-950/90",
    sidebarBg: "bg-rose-950/60",
    chatBg: "bg-slate-950",
    cardBg: "bg-rose-950/30 border-rose-900/30",
    primaryBg: "bg-rose-600 text-white shadow-md",
    primaryHoverBg: "hover:bg-rose-500",
    primaryText: "text-rose-400",
    accentText: "text-pink-300",
    borderCol: "border-rose-900/30",
    ringCol: "ring-rose-500/50",
    activeItemBg: "bg-rose-600/20 border-rose-500/50",
    chatWallpaper: "bg-gradient-to-b from-rose-950/10 via-slate-950 to-slate-950",
    ownBubbleBg: "bg-rose-600 text-white border-rose-400/20",
    badgeBg: "bg-rose-600 text-white"
  },
  nordic: {
    name: "سرمای شمال (Nordic Arctic)",
    id: "nordic",
    mainBg: "bg-slate-950",
    sidebarBg: "bg-sky-950/30",
    chatBg: "bg-slate-950",
    cardBg: "bg-sky-950/20 border-sky-900/30",
    primaryBg: "bg-cyan-600 text-white shadow-md",
    primaryHoverBg: "hover:bg-cyan-500",
    primaryText: "text-cyan-400",
    accentText: "text-sky-300",
    borderCol: "border-sky-900/30",
    ringCol: "ring-cyan-500/50",
    activeItemBg: "bg-cyan-600/20 border-cyan-500/50",
    chatWallpaper: "bg-gradient-to-br from-slate-950 via-slate-950 to-sky-950/10",
    ownBubbleBg: "bg-cyan-600 text-white border-cyan-400/20",
    badgeBg: "bg-cyan-600 text-white"
  },
  pitch_black: {
    name: "مشکی مطلق (Pitch Black)",
    id: "pitch_black",
    mainBg: "bg-black",
    sidebarBg: "bg-neutral-950/90",
    chatBg: "bg-black",
    cardBg: "bg-neutral-900/30 border-zinc-900",
    primaryBg: "bg-zinc-100 text-black shadow-md",
    primaryHoverBg: "hover:bg-zinc-200",
    primaryText: "text-zinc-100",
    accentText: "text-zinc-400",
    borderCol: "border-zinc-900",
    ringCol: "ring-zinc-400/50",
    activeItemBg: "bg-zinc-800/40 border-zinc-700",
    chatWallpaper: "bg-black",
    ownBubbleBg: "bg-zinc-800 text-white border-zinc-700",
    badgeBg: "bg-zinc-200 text-black"
  },
  royal_gold: {
    name: "سلطنتی بنفش (Royal Purple)",
    id: "royal_gold",
    mainBg: "bg-purple-950",
    sidebarBg: "bg-indigo-950/40",
    chatBg: "bg-purple-950",
    cardBg: "bg-indigo-950/20 border-amber-500/20",
    primaryBg: "bg-amber-500 text-black font-black shadow-md",
    primaryHoverBg: "hover:bg-amber-400",
    primaryText: "text-amber-400",
    accentText: "text-purple-300",
    borderCol: "border-amber-500/20",
    ringCol: "ring-amber-500/50",
    activeItemBg: "bg-amber-500/20 border-amber-500/50",
    chatWallpaper: "bg-[radial-gradient(circle_at_top,_var(--tw-gradient-stops))] from-indigo-950/30 via-purple-950 to-purple-950",
    ownBubbleBg: "bg-amber-600 text-white border-amber-400/20",
    badgeBg: "bg-amber-500 text-black"
  },
  forest: {
    name: "سبز جنگلی (Deep Forest)",
    id: "forest",
    mainBg: "bg-zinc-950",
    sidebarBg: "bg-emerald-950/40",
    chatBg: "bg-zinc-950",
    cardBg: "bg-emerald-950/20 border-emerald-900/30",
    primaryBg: "bg-emerald-600 text-white shadow-md",
    primaryHoverBg: "hover:bg-emerald-500",
    primaryText: "text-emerald-400",
    accentText: "text-green-400",
    borderCol: "border-emerald-900/30",
    ringCol: "ring-emerald-500/50",
    activeItemBg: "bg-emerald-600/20 border-emerald-500/50",
    chatWallpaper: "bg-gradient-to-tl from-zinc-950 via-zinc-950 to-emerald-950/15",
    ownBubbleBg: "bg-emerald-600 text-white border-emerald-400/20",
    badgeBg: "bg-emerald-600 text-white"
  },
  mono: {
    name: "مونوکروم ساده (Minimal)",
    id: "mono",
    mainBg: "bg-zinc-950",
    sidebarBg: "bg-zinc-900/90",
    chatBg: "bg-zinc-950",
    cardBg: "bg-zinc-900/40 border-zinc-800",
    primaryBg: "bg-zinc-200 text-zinc-950 font-bold shadow-md",
    primaryHoverBg: "hover:bg-zinc-300",
    primaryText: "text-zinc-200",
    accentText: "text-zinc-400",
    borderCol: "border-zinc-800",
    ringCol: "ring-zinc-400/50",
    activeItemBg: "bg-zinc-800/50 border-zinc-700",
    chatWallpaper: "bg-gradient-to-b from-zinc-950 via-zinc-950 to-zinc-900",
    ownBubbleBg: "bg-zinc-800 text-white border-zinc-700",
    badgeBg: "bg-zinc-200 text-zinc-900"
  }
};
